import type { Metadata } from "next";
import "./../styles/style.scss";
import HSToast from "@/components/Toastify";
import StoreProvider from "@/Redux/StoreProvide";
import ModalsInit from "@/components/ModalsInit";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <StoreProvider>
                <body>
                    {children}
                    <div className="Middlewares">
                        <HSToast />
                        <ModalsInit />
                    </div>
                </body>
            </StoreProvider>
        </html>
    );
}
