import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../styles/style.scss";
import Header from "@components/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body >
                <div className="general-container">
                    <Header />
                    {children}
                </div>
            </body>
        </html>
    );
}
